# requires to upload artifacts in the calling workflow
# with static name "vt-artifacts"

name: "Virustotal Scan"

on:
  workflow_dispatch:  # button shown only when in default branch
  workflow_call:      # we are a reusable template
    inputs:
      repo:
        required: true
        type: string
      wfid:
        required: true
        type: string
      filepattern:
        required: false
        type: string

jobs:
  upload:
    runs-on: ubuntu-latest
    name: "Upload & Scan"
    steps:

      - name: get files
        uses: actions/download-artifact@v4
        with:
          name: vt-artifacts
          merge-multiple: true
          #github-token: ${{ secrets.GH_PAT }} # token with actions:read permissions on target repo
          repository:  ${{ inputs.repo }}
          run-id: ${{ inputs.wfid }}
          path: cwf/${{ inputs.filepattern || '*' }}

      - name: Scan by VirusTotal
        id: vt
        uses: crazy-max/ghaction-virustotal@v4.0.0
        with:
          # The GitHub token used to create an authenticated client for GitHub API
          vt_api_key: "${{ secrets.AXP_VT_API_KEY }}"
          # Newline-delimited list of path globs for asset files to upload for analysis
          files: cwf/*
          # If enabled, analysis link(s) will be appended to the release body
          #update_release_body: true # default is false
          # The GitHub token used to create an authenticated client for GitHub API
          # github_token: # optional, default is ${{ github.token }}
          # API request-rate in requests/minute
          request_rate: 2
