# https://github.com/marketplace/actions/fork-repo-upstream-sync
name: "Sync upstream"

on:
  workflow_dispatch:  # button shown only when in default branch
  schedule:
    - cron:  '0 0 * * *'  # run once per day at midnight

# Sets permissions of the GITHUB_TOKEN to allow pushing via github token
permissions:
  contents: write # allow git push

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        reposync:
          - remote-domain: gitea.angry.im
            remote-repo: PeterCxy/OpenEUICC
            remote-branch: master
            local-repo: AXP-OS/packages_apps_OpenEUICC
            local-branch: mixed

          #local-branch: [ master, axp ] # no idea how I can access that later as matrix.reposync.local-branch is just the array
          - remote-domain: github.com
            remote-repo: Divested-Mobile/DivestOS-Build
            remote-branch: master
            local-repo: AXP-OS/build
            local-branch: master
          - remote-domain: github.com
            remote-repo: Divested-Mobile/DivestOS-Build
            remote-branch: master
            local-repo: AXP-OS/build
            local-branch: axp

    name: "Sync ${{ matrix.reposync.remote-repo }} (${{ matrix.reposync.local-branch }})"

    steps:
    - name: Checkout common scripts
      uses: actions/checkout@v4
      with:
        path: scripts
        
    - name: Checkout ${{ matrix.reposync.local-repo }}
      uses: actions/checkout@v4
      with:
        repository: "${{ matrix.reposync.local-repo }}"
        ref: "${{ matrix.reposync.local-branch }}"
        # REQUIRED if your upstream repo is private (see wiki)
        persist-credentials: false
        #token: ${{ secrets.GITHUB_TOKEN }}

    - name: Sync with ${{ matrix.reposync.remote-repo }}
      id: sync
      env:
        ghtoken: ${{ secrets.GITHUB_TOKEN }}
      run: |
        bash scripts/merge_and_push.sh \
          "${{ matrix.reposync.local-domain}}/${{ matrix.reposync.local-repo }}:${{ matrix.reposync.local-branch }}"\
          "${{ matrix.reposync.remote-domain}}/${{ matrix.reposync.remote-repo }}:${{ matrix.reposync.remote-branch }}"\
          DRYRUN


#    - name: Sync with ${{ matrix.reposync.remote-repo }}
#      id: sync
#      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
#      with:
#        target_sync_branch: "${{ matrix.reposync.local-branch }}"
#        # REQUIRED 'target_repo_token' exactly like this!
#        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
#        upstream_sync_branch: "${{ matrix.reposync.remote-branch }}"
#        upstream_sync_repo_domain: "${{ matrix.reposync.remote-domain }}"
#        upstream_sync_repo: "${{ matrix.reposync.remote-repo }}"
#        #upstream_repo_access_token: ${{ secrets.UPSTREAM_REPO_SECRET }}
#        shallow_since: '3 years ago'
#        # Set test_mode true to run tests instead of the true action!!
#        test_mode: true
      
#    - name: "New commits found?"
#      if: steps.sync.outputs.has_new_commits == 'true'
#      run: echo "New commits found!"

    # Merge with main branch when new commits were found
#    - name: "Merge ${{ matrix.reposync.local-branch }} -> ${{ matrix.reposync.local-branch-final }}"
#      if: steps.sync.outputs.has_new_commits == 'true' && ${{ matrix.reposync.local-branch-final }}
#      uses: devmasx/merge-branch@master
#      with:
#          type: now
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          from_branch: "${{ matrix.reposync.local-branch }}"
#          target_branch: "${{ matrix.reposync.local-branch-final }}"
#          message: "merge with upstream"
 
